In [177]:
import numpy as np 
import pandas as pd 

import pandas as pd
import re
from nltk.corpus import stopwords
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer

In [178]:
df=pd.read_csv("./final_dataset (1).csv",encoding='latin-1')
#cols=['Tweet Id', 'Tweets','User Id', 'Screen Name', 'Class']
df=df.dropna(axis=0, how='any')

In [179]:
num_tweets=df["Tweets"].size
def tweet_processing(raw_tweet):
    letters_only=re.sub("[^a-zA-Z]"," ",raw_tweet)
    words=letters_only.lower().split()
    stops=set(stopwords.words("english"))
    m_w=[w for w in words if not w in stops]
    return (" ".join(m_w))

In [180]:
clean_tweet=[]
for i in range(0,num_tweets):
    clean_tweet.append(tweet_processing(df["Tweets"][i]))

df["Tweets"]=clean_tweet

In [181]:
df.head()

ID                                             Tweets    User Id  \
0  3.190000e+17                      oh yeah colin smash girls mkr  949380854   
1  3.210000e+17      insane keep bringing people back show end mkr  297877558   
2  3.240000e+17  berkeley eagle mkr shit show comebacks johnny ...  272704749   
3  3.260000e+17                                  sigh oh colin mkr   71416635   
4  3.820000e+17  rt brian day swear sexist honestly cannot stan...  930620467   

      Screen Name   Class  Label  
0    CreatrixKali  sexism      0  
1   quincepoacher    none      2  
2      MarkTramby    none      2  
3          BinnyD    none      2  
4  YesYoureSexist  sexism      0

In [87]:
mask = np.random.rand(len(df)) < 0.8
train, test = df[mask], df[~mask]
train.to_csv('./tweets_train', sep='\t', index=False, header=False)
test.to_csv('./tweets_test', sep='\t', index=False, header=False)

In [65]:
tf=pd.read_csv("./tfidf.csv", encoding = "ISO-8859-1", index_col=0)

In [31]:
s_t = list(tf['Sexist_terms'])
r_t = list(tf['Racist_terms']) 
o_t = list(tf['Other_terms'])
classes = [s_t,r_t,o_t]

bad_list = ['colin','im','dont','ok','u','af','na','ur','p','^.^','lt','am','|']

for i in classes:
    for k in i:
        if k in bad_list:
            i.remove(k)

In [175]:
tweets = list(df['Tweets']) 

for l in classes:
    print ("LL",l)
    for i in l:
        print ("I",i)
        t = []
        for d in tweets:
            tfm = re.search(i, d)
            if tfm:
                t.append(1)
            else:
                t.append(0)
        df[i] = t    

    
names = df.columns.values 
#print(names)

LL ['sorri', 'honestli', 'femin', 'ref', 'footbal', 'kitchen', 'cunt', 'horribl', 'dude', 'driver', 'sport', 'sportscent', 'aw', 'chick', 'espn', 'annoy', 'ladi', 'comedian', 'coach', 'dish', 'score', 'blond', 'rugbi', 'standard', 'omg', 'analyst', 'swear', "y'all", 'hoe', 'af', 'shave', 'hair', 'weird', 'ghost', 'mom', 'idk', 'rap', 'wow', 'basketbal', 'slut', 'wrestl', 'fem', 'tit', 'wnba', 'gender', 'ufc', 'charact', 'sister', 'though', 'crazi', 'fan', 'team', 'gon', 'argu', 'wonder', 'smile', 'andr', 'rapper', 'cant', 'hockey', 'eye', 'leagu', 'tonight', 'miss', 'tan', 'thor', 'skank', 'ghostbust', 'bimbo', 'parenthood', 'abort', 'gap', 'romney', 'movement', 'adopt', 'ford', 'valenti', 'kati', 'nikki', 'hooker', 'sausag', 'trashi', 'sassi', 'tart', 'deconstruct', 'promo', 'anni', 'kat', 'strateg', 'lloyd', 'celin']
I sorri
I honestli
I femin
I ref
I footbal
I kitchen
I cunt
I horribl
I dude
I driver
I sport
I sportscent
I aw
I chick
I espn
I annoy
I ladi
I comedian
I coach
I dish
I

In [148]:
df.head()

ID                                             Tweets    User Id  \
0  3.190000e+17                      oh yeah colin smash girls mkr  949380854   
1  3.210000e+17      insane keep bringing people back show end mkr  297877558   
2  3.240000e+17  berkeley eagle mkr shit show comebacks johnny ...  272704749   
3  3.260000e+17                                  sigh oh colin mkr   71416635   
4  3.820000e+17  rt brian day swear sexist honestly cannot stan...  930620467   

      Screen Name   Class  Label  sorri  honestli  femin  ref  ...   gdc  \
0    CreatrixKali  sexism      0      0         0      0    0  ...     0   
1   quincepoacher    none      2      0         0      0    0  ...     0   
2      MarkTramby    none      2      0         0      0    0  ...     0   
3          BinnyD    none      2      0         0      0    0  ...     0   
4  YesYoureSexist  sexism      0      0         0      0    0  ...     0   

   appl  edit  bacon  oapi  liver  jac  shaz  yummi  mapl  
0     0     0      0     0      0    0     0      0     0  
1     0     0      0     0      0    0     0      0     0  
2     0     0      0     0      0    0     0      0     0  
3     0     0      0     0      0    0     0      0     0  
4     0     0      0     0      0    0     0      0     0  

[5 rows x 258 columns]

In [149]:
tweets = list(df.Tweets)

analyzer = SentimentIntensityAnalyzer()
negative = []
compound = []

for i in range(len(tweets)):
    vs = analyzer.polarity_scores(tweets[i])
    negative.append(vs.get("neg"))
    compound.append(vs.get("compound"))

In [150]:
df['Neg_Sent'] = negative
df['Compound'] = compound

In [36]:
df.to_csv("final_dataset_hs.csv")

In [176]:
df.head()

ID                                             Tweets    User Id  \
0  3.190000e+17                      oh yeah colin smash girls mkr  949380854   
1  3.210000e+17      insane keep bringing people back show end mkr  297877558   
2  3.240000e+17  berkeley eagle mkr shit show comebacks johnny ...  272704749   
3  3.260000e+17                                  sigh oh colin mkr   71416635   
4  3.820000e+17  rt brian day swear sexist honestly cannot stan...  930620467   

      Screen Name   Class  Label  sorri  honestli  femin  ref  ...   gdc  \
0    CreatrixKali  sexism      0      0         0      0    0  ...     0   
1   quincepoacher    none      2      0         0      0    0  ...     0   
2      MarkTramby    none      2      0         0      0    0  ...     0   
3          BinnyD    none      2      0         0      0    0  ...     0   
4  YesYoureSexist  sexism      0      0         0      0    0  ...     0   

   appl  edit  bacon  oapi  liver  jac  shaz  yummi  mapl  
0     0     0      0     0      0    0     0      0     0  
1     0     0      0     0      0    0     0      0     0  
2     0     0      0     0      0    0     0      0     0  
3     0     0      0     0      0    0     0      0     0  
4     0     0      0     0      0    0     0      0     0  

[5 rows x 258 columns]

In [124]:
#Create train and test sets
Columns=['Tweets']
x=df[Columns]
y=df['Label']
X_train, X_test, Y_train, Y_test = train_test_split(x, y, test_size=0.2)

In [104]:
df=pd.read_csv("./final_dataset_hs.csv")

In [116]:
X_train.shape

(9060, 2)

In [115]:
vectorizer=CountVectorizer(analyzer = "word",tokenizer = None,preprocessor = None,stop_words = None,max_features = 5000)

train_data_features=vectorizer.fit_transform(X_train)
train_data_features=train_data_features.toarray()

test_data_features=vectorizer.transform(X_test)
test_data_features=test_data_features.toarray()

AttributeError: 'numpy.ndarray' object has no attribute 'lower'

In [107]:
#SVM with linear kernel
clf=svm.SVC(kernel='linear',C=1.0)
print ("Training")
clf.fit(train_data_features,Y_train)

print ("Testing")
predicted=clf.predict(test_data_features)
accuracy=np.mean(predicted==Y_test)
print ("Accuracy: ",accuracy)

Training


ValueError: Found input variables with inconsistent numbers of samples: [2, 9060]

In [10]:
from sklearn.metrics import precision_recall_fscore_support
precision_recall_fscore_support(Y_test, predicted, average='micro')

(0.8678745028722934, 0.8678745028722934, 0.8678745028722934, None)

In [41]:
df=pd.read_csv("./final_dataset_hs.csv")
#tf=pd.read_csv("./tfidf.csv", encoding = "ISO-8859-1", index_col=0)

In [14]:
s_t = list(tf['Sexist_terms'])
r_t = list(tf['Racist_terms']) 
o_t = list(tf['Other_terms'])
classes = [s_t,r_t,o_t]

bad_list = ['colin','im','dont','ok','u','af','na','ur','p','^.^','lt','am','|']

for i in classes:
    for k in i:
        if k in bad_list:
            i.remove(k)

In [15]:
tweets = list(df['Tweets']) 

for l in classes:
    for i in l:
        t = []
        for d in tweets:
            tfm = re.search(i, d)
            if tfm:
                t.append(1)
            else:
                t.append(0)
        df[i] = t    

    
names = df.columns.values 
#print(names)

In [16]:
hashtags = list(df['Hashtags'])
htags = []

for hashtag in hashtags:
    texts = re.findall(r"'\w+'", hashtag)
    for i in texts:
        if i != 'text' and i != 'indices':
            htags.append(i.lower())

htags=set(htags)

In [17]:
list_h = list(df['Hashtags'])

for i in htags:
    list_i = []
    for k in list_h:
        ht = re.search(i,k)
        if ht:
            list_i.append(1)
        else:
            list_i.append(0)
    df[i] = list_i

In [151]:
import string
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer
tweets = list(df.Tweets)

analyzer = SentimentIntensityAnalyzer()
negative = []
compound = []

for i in range(len(tweets)):
    vs = analyzer.polarity_scores(tweets[i])
    negative.append(vs.get("neg"))
    compound.append(vs.get("compound"))

In [152]:
df['Neg_Sent'] = negative
df['Compound'] = compound


In [153]:
df.head()

ID                                             Tweets    User Id  \
0  3.190000e+17                      oh yeah colin smash girls mkr  949380854   
1  3.210000e+17      insane keep bringing people back show end mkr  297877558   
2  3.240000e+17  berkeley eagle mkr shit show comebacks johnny ...  272704749   
3  3.260000e+17                                  sigh oh colin mkr   71416635   
4  3.820000e+17  rt brian day swear sexist honestly cannot stan...  930620467   

      Screen Name   Class  Label  sorri  honestli  femin  ref    ...     edit  \
0    CreatrixKali  sexism      0      0         0      0    0    ...        0   
1   quincepoacher    none      2      0         0      0    0    ...        0   
2      MarkTramby    none      2      0         0      0    0    ...        0   
3          BinnyD    none      2      0         0      0    0    ...        0   
4  YesYoureSexist  sexism      0      0         0      0    0    ...        0   

   bacon  oapi  liver  jac  shaz  yummi  mapl  Neg_Sent  Compound  
0      0     0      0    0     0      0     0     0.000    0.2960  
1      0     0      0    0     0      0     0     0.278   -0.4019  
2      0     0      0    0     0      0     0     0.243   -0.3400  
3      0     0      0    0     0      0     0     0.000    0.0258  
4      0     0      0    0     0      0     0     0.079    0.4215  

[5 rows x 260 columns]

In [24]:
df.to_csv("full_dataset.csv")

In [71]:
from keras.layers import Dense
from keras.models import Sequential
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical

In [163]:
rel_var = df.iloc[:,6:257]
print(rel_var.head())

   sorri  honestli  femin  ref  footbal  kitchen  cunt  horribl  dude  driver  \
0      0         0      0    0        0        0     0        0     0       0   
1      0         0      0    0        0        0     0        0     0       0   
2      0         0      0    0        0        0     0        0     0       0   
3      0         0      0    0        0        0     0        0     0       0   
4      0         0      0    0        1        0     0        0     0       0   

   ...    upset  gdc  appl  edit  bacon  oapi  liver  jac  shaz  yummi  
0  ...        0    0     0     0      0     0      0    0     0      0  
1  ...        0    0     0     0      0     0      0    0     0      0  
2  ...        0    0     0     0      0     0      0    0     0      0  
3  ...        0    0     0     0      0     0      0    0     0      0  
4  ...        0    0     0     0      0     0      0    0     0      0  

[5 rows x 251 columns]


In [155]:
predictors = pd.DataFrame.as_matrix(rel_var, columns=None)

C:\Users\Shreya Majumder\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: Method .as_matrix will be removed in a future version. Use .values instead.
  """Entry point for launching an IPython kernel.


In [156]:
from keras.layers import Dense
from keras.models import Sequential
from keras.callbacks import EarlyStopping
from keras.utils import to_categorical
new_class = []

for i in df.Class:
    if i == 'sexism':
        new_class.append(0)
    elif i == 'racism':
        new_class.append(1)
    else:
        new_class.append(2)

target=to_categorical(new_class)
n_cols = predictors.shape[1]

In [159]:
print (n_cols)

251


In [158]:
print (target)

[[1. 0. 0.]
 [0. 0. 1.]
 [0. 0. 1.]
 ...
 [0. 0. 1.]
 [1. 0. 0.]
 [1. 0. 0.]]


In [49]:
model = Sequential()
model.add(Bidirectional(LSTM(64)))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))


#Add layers to model
model.add(Dense(100, activation='relu', input_shape = (n_cols,)))
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(1000, activation='relu'))
model.add(Dense(3, activation='softmax'))

In [79]:
model = Sequential()
model.add(Bidirectional(LSTM(64)))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])
early_stop = EarlyStopping(patience=3) 
model.fit(predictors, target,
            epochs=30,
            callbacks=[early_stop])

#early_stop = EarlyStopping(patience=3) 

#fit model
#model.fit(predictors, target, validation_split=0.3, epochs=30, callbacks=[early_stop])

ValueError: Input 0 is incompatible with layer bidirectional_6: expected ndim=3, found ndim=2

In [91]:
import numpy as np
import random
from keras.layers import Dense, Dropout, Embedding, LSTM, Bidirectional
from keras.models import Sequential
from keras.preprocessing import sequence
from keras.preprocessing.text import one_hot

max_features = 50000
maxlen = 10
batch_size = 32
#Create train and test sets
#train = './tweets_train.csv'
#test = './tweets_test.csv'

X_train, X_test, Y_train, Y_test = train_test_split(df.Tweets, df.Label, test_size=0.2)
#x_train, y_train = read_data(train, max_features)
#x_test, y_test = read_data(test, max_features)
X_train = sequence.pad_sequences(X_train, maxlen=maxlen)
X_test = sequence.pad_sequences(X_test, maxlen=maxlen)
Y_train = np.array(Y_train)
Y_test = np.array(Y_test)

model = Sequential()
model.add(Embedding(max_features, 128, input_length=maxlen))
model.add(Bidirectional(LSTM(64)))
model.add(Dropout(0.5))
model.add(Dense(1, activation='sigmoid'))

model.compile('adam', 'binary_crossentropy', metrics=['accuracy'])

model.fit(x_train, y_train,
            batch_size=batch_size,
            epochs=30,
            validation_data=[x_test, y_test])

TypeError: object of type 'int' has no len()

In [161]:
df.head()

ID                                             Tweets    User Id  \
0  3.190000e+17                      oh yeah colin smash girls mkr  949380854   
1  3.210000e+17      insane keep bringing people back show end mkr  297877558   
2  3.240000e+17  berkeley eagle mkr shit show comebacks johnny ...  272704749   
3  3.260000e+17                                  sigh oh colin mkr   71416635   
4  3.820000e+17  rt brian day swear sexist honestly cannot stan...  930620467   

      Screen Name   Class  Label  sorri  honestli  femin  ref    ...     edit  \
0    CreatrixKali  sexism      0      0         0      0    0    ...        0   
1   quincepoacher    none      2      0         0      0    0    ...        0   
2      MarkTramby    none      2      0         0      0    0    ...        0   
3          BinnyD    none      2      0         0      0    0    ...        0   
4  YesYoureSexist  sexism      0      0         0      0    0    ...        0   

   bacon  oapi  liver  jac  shaz  yummi  mapl  Neg_Sent  Compound  
0      0     0      0    0     0      0     0     0.000    0.2960  
1      0     0      0    0     0      0     0     0.278   -0.4019  
2      0     0      0    0     0      0     0     0.243   -0.3400  
3      0     0      0    0     0      0     0     0.000    0.0258  
4      0     0      0    0     0      0     0     0.079    0.4215  

[5 rows x 260 columns]

In [120]:
from keras.preprocessing.text import Tokenizer
from keras.preprocessing.sequence import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten, LSTM, Conv1D, MaxPooling1D, Dropout, Activation
from keras.layers.embeddings import Embedding

# NLTK



# Other
import re
import timeit
import string
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split

In [125]:
def process_sample(sample):
    
    print("\nGiven sample size:", len(sample))
    
    #Keras tokenizer function to tokenize the strings and 
    #‘texts_to_sequences’ to make sequences of words.

    vocabulary_size = 20000

    #Maximum number of words to work with 
    #if set, tokenization will be restricted to the top nb_words most common words in the dataset).
    tokenizer = Tokenizer(num_words= vocabulary_size)

    #fit_on_texts(texts):
    #Arguments: list of texts to train on.
    #tokenizer.fit_on_texts(data['tweet'])
    tokenizer.fit_on_texts(sample)

    #texts_to_sequences(texts)
    #texts: list of texts to turn to sequences.
    #Return: list of sequences (one per text input).
    
    #sequences = tokenizer.texts_to_sequences(data['tweet'])
    sequences = tokenizer.texts_to_sequences(sample)
    sample = pad_sequences(sequences, maxlen=50)
    
    print("Processed sample shape:", sample.shape)
    #print("Sample1:", sample[0])
    
    return sample

In [145]:
X = df['Tweets']
Y = df['Label']
X_train, X_test, Y_train, Y_test = train_test_split(X, Y, test_size = 0.2)

print("Train data len:", len(X_train), "\nTest data len:", len(X_test))

X_train_seq = process_sample(X_train)
X_test_seq = process_sample(X_test)

Train data len: 9060 
Test data len: 2265

Given sample size: 9060
Processed sample shape: (9060, 50)

Given sample size: 2265
Processed sample shape: (2265, 50)


In [160]:
#LSTM Network architecture

print('Building model...')
model_lstm = Sequential()

#The network starts with an embedding layer.
#Turns positive integers (indexes) into dense vectors of fixed size allowing the n/w to represent a word in a meaningful way.
#eg. [[4], [20]] -> [[0.25, 0.1], [0.6, -0.2]]
#This layer can only be used as the first layer in a model.

#keras.layers.Embedding(input_dim, output_dim, embeddings_initializer='uniform', ***, input_length=None)

#input_dim: int > 0. Size of the vocabulary, i.e. maximum integer index + 1.

#output_dim: int >= 0. Dimension of the dense embedding.

#input_length: Length of input sequences, when it is constant. 
#This argument is required if you are going to connect Flatten then Dense layers upstream 
#(without it, the shape of the dense outputs cannot be computed).

#eg. model.add(Embedding(1000, 64, input_length=10))

# the model will take as input an integer matrix of size (batch, input_length).
# where the largest integer (i.e. word index) in the input should be no larger than 999 (vocabulary size).

# o/p will be model.output_shape == (None, 10 :input_dim, 64:output_dim), where None is the batch dimension of the matrix given.


model_lstm.add(Embedding(20000, 100, input_length=251))
model_lstm.add(LSTM(100, dropout=0.5))
model_lstm.add(Dense(1, activation='sigmoid'))

model_lstm.compile(loss='categorical_crossentropy', optimizer='adam', metrics=['accuracy'])
early_stop = EarlyStopping(patience=2) 

#fit model
model.fit(predictors, target, validation_split=0.3, epochs=20, callbacks=[early_stop])


Building model...


AttributeError: 'Sequential' object has no attribute '_feed_input_names'

In [168]:
model = Sequential()

#Add layers to model
model.add(Embedding(20000, 100, input_length=n_cols))
model.add(Dropout(0.25))#, input_shape=(sequence_length, embedding_dim)))
model.add(LSTM(50))
model.add(Dropout(0.5))
model.add(Dense(3))
model.add(Activation('softmax'))
#compile 
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics = ['accuracy'])

early_stop = EarlyStopping(patience=2) 

#fit model
model.fit(predictors, target, validation_split=0.3, epochs=100, callbacks=[early_stop])

Train on 7927 samples, validate on 3398 samples
Epoch 1/100
7927/7927 [==============================] - 48s 6ms/step - loss: 0.6754 - acc: 0.6754 - val_loss: 0.4724 - val_acc: 0.8514
Epoch 2/100
7927/7927 [==============================] - 46s 6ms/step - loss: 0.6444 - acc: 0.6840 - val_loss: 0.4893 - val_acc: 0.8514
Epoch 3/100
7927/7927 [==============================] - 47s 6ms/step - loss: 0.6384 - acc: 0.6841 - val_loss: 0.4716 - val_acc: 0.8514
Epoch 4/100
7927/7927 [==============================] - 47s 6ms/step - loss: 0.6412 - acc: 0.6841 - val_loss: 0.5076 - val_acc: 0.8514
Epoch 5/100
7927/7927 [==============================] - 48s 6ms/step - loss: 0.6400 - acc: 0.6841 - val_loss: 0.5052 - val_acc: 0.8514
